Repository UnBArqDsw2021-1/2021.1_G6_Curumim, pull requests merged in 2021-09, with the labels that each got.

#138 Documentação da planning sprint 4
  docs/reunioes/sprints/planning-sprint4.md
Labels: documentation

#142 Review da sprint 4
  docs/assets/imagens/sprint-review/sprint3/burndown-report.png
  docs/assets/imagens/sprint-review/sprint4/burndown-report.png
  docs/assets/imagens/sprint-review/sprint4/velocity-tracking.png
  docs/reunioes/sprints/planning-sprint0.md
  docs/reunioes/sprints/planning-sprint1.md
  docs/reunioes/sprints/planning-sprint2.md
  docs/reunioes/sprints/planning-sprint3.md
  docs/reunioes/sprints/planning-sprint4.md
  docs/reunioes/sprints/review-sprint4.md
  mkdocs.yml
Labels: documentation

#132 GRASP Criador
  docs/padroes-de-projeto/grasp.md
Labels: documentation

#144 GRASPs - Controlador e Variações Protegidas
  docs/assets/imagens/GRASPs/user_controller.png
  docs/padroes-de-projeto/grasp.md
Labels: documentation

#136 GRASPs - Especialista
  docs/padroes-de-projeto/grasp.md
Labels: documentation

#140 GRASPs - Alta coesao e baixo acoplamento
  docs/padroes-de-projeto/grasp.md
Labels: documentation

#137 GRASPs - polimorfismo
  docs/assets/imagens/GRASPs/polimorfismo.png
  docs/padroes-de-projeto/grasp.md
Labels: documentation

#151 GOFs Criacionais - Factory method
  docs/assets/imagens/gofs/factory-method.png
  docs/padroes-de-projeto/gofs-criacionais.md
Labels: documentation

#155 Fix - Guia de estilo
  docs/padroes-de-projeto/guia-de-estilo/guia-de-estilo.md
Labels: documentation

#159 GOFs Estruturais - Adapters
  docs/assets/imagens/gofs-adapters/adapters-controller.png
  docs/assets/imagens/gofs-adapters/adapters-model-adm.png
  docs/padroes-de-projeto/gofs-estruturais.md
Labels: documentation

#153 Planning sprint 5
  docs/reunioes/sprints/planning-sprint5.md
  mkdocs.yml
Labels: documentation

#158 GOFs Estruturais- Proxy
  docs/assets/imagens/gofs/composite-codigo.jpeg
  docs/assets/imagens/gofs/factory-method.png
  docs/assets/imagens/gofs/proxy-code.png
  docs/assets/imagens/gofs/proxy.png
  docs/padroes-de-projeto/gofs-criacionais.md
  docs/padroes-de-projeto/gofs-estruturais.md
  mkdocs.yml
Labels: documentation

#166 Revisão dos diagramas - Diagrama de casos de uso
  docs/assets/imagens/casos-de-uso/casos-de-uso.png
Labels: documentation, extra, Feedback

#164 doc(#162): atualizando informações de acordo com o feedback da entrega 1
  docs/base/metodologia/bpmn.md
  docs/base/metodologia/metodologia.md
  docs/base/requisitos/elicitacao/brainstorming.md
  docs/base/requisitos/elicitacao/introspeccao.md
  docs/base/requisitos/elicitacao/personas.md
  docs/base/requisitos/modelagem/especificacao-suplementar.md
  docs/base/requisitos/pre-rastreabilidade/rich-picture.md
  docs/base/requisitos/priorizacao/first-things-first.md
  docs/causa-efeito.md
  docs/politicas.md
Labels: documentation

#173 Visitor, Memento e Chain of Responsibility
  docs/padroes-de-projeto/gofs-comportamentais.md
Labels: documentation

#174 Revisão do diagrama lógico do banco de dados
  docs/assets/imagens/diagrama-logico-bd/diagrama-logico-bd-curumin-v1.png
  docs/assets/imagens/diagrama-logico-bd/diagrama-logico-bd-curumin-v2.png
  docs/modelagem/modelagem-estatica/diagrama-logico-bd.md
Labels: documentation

#160 GOFs Estruturais - Composite
  docs/assets/imagens/gofs/CompositeModelagem.png
  docs/assets/imagens/gofs/composite-code.png
  docs/padroes-de-projeto/gofs-estruturais.md
Labels: documentation

#157 Review sprint 5
  docs/assets/imagens/sprint-review/sprint5/burndown-report.png
  docs/assets/imagens/sprint-review/sprint5/velocity-tracking.png
  docs/reunioes/sprints/review-sprint3.md
  docs/reunioes/sprints/review-sprint5.md
  mkdocs.yml
Labels: documentation

#156 Doc/147 pacotes
  docs/assets/imagens/diagrama-de-pacotes/diagrama_de_pacotes_v2.png
  docs/modelagem/modelagem-estatica/diagrama-de-pacotes.md
Labels: documentation

#177 Singleton, Multiton e Object Pool
  docs/padroes-de-projeto/gofs-criacionais.md
Labels: documentation

#163 Doc/150 abstract factory e Prototype
  docs/assets/imagens/gofs/abstract-factory.png
  docs/assets/imagens/gofs/auth-controller.png
  docs/assets/imagens/gofs/prototype.png
  docs/padroes-de-projeto/gofs-criacionais.md
Labels: documentation

#171 Revisão dos diagramas - Diagrama de estados
  docs/assets/imagens/diagrama-estados/cadastro-crianca-professor.png
  docs/assets/imagens/diagrama-estados/comunicacao.png
  docs/assets/imagens/diagrama-estados/gerencia-turma.png
  docs/assets/imagens/diagrama-estados/lancamento-presenca.png
  docs/modelagem/modelagem-dinamica/diagrama-estados.md
Labels: documentation, Feedback

#179 PR2: doc(#162): adicionando revisores no versionamento
  docs/base/metodologia/bpmn.md
  docs/base/metodologia/metodologia.md
  docs/base/requisitos/elicitacao/brainstorming.md
  docs/base/requisitos/elicitacao/introspeccao.md
  docs/base/requisitos/elicitacao/personas.md
  docs/base/requisitos/modelagem/especificacao-suplementar.md
  docs/base/requisitos/pre-rastreabilidade/rich-picture.md
  docs/base/requisitos/priorizacao/first-things-first.md
  docs/causa-efeito.md
  docs/politicas.md
Labels: documentation

#165 Padrões Observer, State, Command e Iterator
  docs/assets/imagens/gofs/gof-iterator.png
  docs/assets/imagens/gofs/gof-observer.png
  docs/assets/imagens/gofs/gof-state-diagram.png
  docs/assets/imagens/gofs/gof-state.jpg
  docs/padroes-de-projeto/gofs-comportamentais.md
Labels: documentation

#176 Padroes emergentes
  docs/assets/imagens/padroes-emergentes/controller.png
  docs/assets/imagens/padroes-emergentes/express-2.png
  docs/assets/imagens/padroes-emergentes/express1.png
  docs/assets/imagens/padroes-emergentes/mc.png
  docs/assets/imagens/padroes-emergentes/middleware-manage.png
  docs/assets/imagens/padroes-emergentes/model.png
  docs/assets/imagens/padroes-emergentes/mvc.png
  docs/padroes-de-projeto/padroes_emergentes.md
  mkdocs.yml
Labels: documentation

#172 Revisão do diagrama de classes
  docs/assets/imagens/diagrama-de-classes/diagrama-classes-v2.png
  docs/modelagem/modelagem-estatica/diagrama-de-classes.md
Labels: documentation

#182 Strategy e Template Method
  docs/padroes-de-projeto/gofs-comportamentais.md
Labels: documentation

#184 Padrão Bridge - Gofs Estruturais
  docs/padroes-de-projeto/gofs-estruturais.md
Labels: documentation

#187 FIX : Corrige 145_main
  docs/assets/imagens/gofs/CompositeModelagem.png
  docs/padroes-de-projeto/gofs-estruturais.md
  mkdocs.yml
Labels: documentation

#193 review sprint 6 e planning sprint 7
  docs/reunioes/sprints/planning-sprint6.md
  docs/reunioes/sprints/planning-sprint7.md
  docs/reunioes/sprints/review-sprint6.md
Labels: documentation

#195 Review da sprint 7
  docs/assets/imagens/sprint-review/sprint7/burndown-report.png
  docs/assets/imagens/sprint-review/sprint7/velocity-tracking.png
  docs/reunioes/sprints/planning-sprint7.md
  docs/reunioes/sprints/review-sprint7.md
  mkdocs.yml
Labels: documentation
