Repository UnBArqDsw2021-1/2021.1_G6_Curumim, pull requests merged in 2021-08, with the labels that each got.

#22 Documentação da metodologia e do guia de contribuição
  .github/ISSUE_TEMPLATE/template-basico.md
  .github/ISSUE_TEMPLATE/template-bug.md
  .github/pull_request_template.md
  docs/assets/imagens/metodologia/ciclo_scrum.gif
  docs/assets/imagens/metodologia/zen-hub.png
  docs/base/metodologia/metodologia.md
  docs/guia-contrib.md
  docs/politicas.md
  mkdocs.yml
Labels: documentation

#29 Modelagem BPMN
  docs/assets/imagens/BPMN/bpmn-ds.jpg
  docs/assets/imagens/BPMN/bpmn-ex-metodologia.jpg
  docs/assets/imagens/BPMN/bpmn-geral.jpg
  docs/assets/imagens/BPMN/bpmn-metodologia.jpg
  docs/assets/imagens/BPMN/bpmn-planning.jpg
  docs/assets/imagens/BPMN/bpmn-review.jpg
  docs/assets/imagens/BPMN/bpmn-tema.jpg
  docs/base/metodologia/bpmn.md
  mkdocs.yml
Labels: documentation

#30 Adição dos documentos referentes ao NFR Framework e Argumentação
  docs/assets/imagens/argumentacao/arg-1.png
  docs/assets/imagens/argumentacao/arg-2.png
  docs/assets/imagens/argumentacao/arg-3.png
  docs/assets/imagens/argumentacao/arg-4.png
  docs/assets/imagens/nfr-framework/diagrama-nfr.png
  docs/assets/imagens/nfr-framework/legenda-nfr.png
  docs/base/requisitos/modelagem/nfr-framework.md
  docs/base/requisitos/pre-rastreabilidade/argumentacao.md
  mkdocs.yml
Labels: documentation

#26 Padronizando e fazendo ajustes no documento de Moscow
  docs/base/requisitos/elicitacao/brainstorming.md
  docs/base/requisitos/priorizacao/moscow.md
Labels: documentation

#38 Documentação relacionada a rich pictures
  docs/base/requisitos/pre-rastreabilidade/rich-picture.md
Labels: documentation

#27 Padronização do First Things First
  docs/base/requisitos/priorizacao/first-things-first.md
Labels: documentation

#25 Documentação relacionada à protótipos
  .gitignore
  docs/base/design-sprint/plan-test.md
  docs/base/design-sprint/prototipo-alta.md
  docs/base/design-sprint/prototipo-baixa.md
  docs/base/design-sprint/prototipos.md
Labels: documentation

#32 Documentação sobre iStar
  docs/base/requisitos/modelagem/i-star.md
  mkdocs.yml
Labels: documentation

#44 Documento de especificação suplementar
  docs/base/requisitos/modelagem/especificacao-suplementar.md
Labels: documentation

#43 Documentação causa-efeito
  docs/assets/imagens/causa-efeito/Diagrama Causa-Efeito.png
  docs/base/requisitos/pre-rastreabilidade/causa-efeito.md
Labels: documentation

#39 Documentação das storyboards
  docs/assets/imagens/storyboards/storyboard_gustavo_1.png
  docs/assets/imagens/storyboards/storyboard_gustavo_2.png
  docs/assets/imagens/storyboards/storyboard_poliana_1.png
  docs/assets/imagens/storyboards/storyboard_poliana_2.png
  docs/base/requisitos/elicitacao/story-boards.md
  docs/base/requisitos/elicitacao/storyboards.md
  mkdocs.yml
Labels: documentation

#37 Design Sprint: adição da introdução, metodologia e datas de realização
  docs/base/design-sprint/doc-design-sprint.md
  docs/base/requisitos/elicitacao/introspeccao.md
Labels: documentation, Design Sprint

#45 Plano de Riscos
  docs/assets/imagens/EAR/EAR_02.PNG
  docs/base/tap/tap.md
  mkdocs.yml
Labels: documentation, Sprint 0

#49 Léxicos e primeira apresentação
  README.md
  docs/base/design-sprint/doc-design-sprint.md
  docs/base/design-sprint/plan-test.md
  docs/base/design-sprint/prototipo-alta.md
  docs/base/design-sprint/prototipo-baixa.md
  docs/base/design-sprint/prototipos.md
  docs/base/requisitos/elicitacao/brainstorming.md
  docs/base/requisitos/elicitacao/introspeccao.md
  docs/base/requisitos/elicitacao/personas.md
  docs/base/requisitos/elicitacao/storyboards.md
  docs/base/requisitos/modelagem/especificacao-suplementar.md
  docs/base/requisitos/modelagem/i-star.md
  docs/base/requisitos/modelagem/lexicos.md
  docs/base/requisitos/pre-rastreabilidade/5w2h.md
  docs/base/requisitos/pre-rastreabilidade/argumentacao.md
  docs/base/requisitos/pre-rastreabilidade/rich-picture.md
  docs/base/requisitos/priorizacao/first-things-first.md
  docs/base/requisitos/priorizacao/moscow.md
  docs/base/tap/tap.md
  docs/causa-efeito.md
  docs/guia-contrib.md
  docs/index.md
  docs/product-backlog.md
  docs/reunioes/sprints/planning-sprint0.md
  mkdocs.yml
Labels: documentation

#61 Rótulo de iniciativa extra
  docs/assets/stylesheets/extra.css
  docs/base/design-sprint/plan-test.md
  docs/base/requisitos/elicitacao/introspeccao.md
  docs/base/requisitos/elicitacao/personas.md
  docs/base/requisitos/modelagem/especificacao-suplementar.md
  docs/base/requisitos/modelagem/i-star.md
  docs/base/requisitos/modelagem/lexicos.md
  docs/base/requisitos/modelagem/nfr-framework.md
  docs/base/requisitos/pre-rastreabilidade/argumentacao.md
  docs/base/requisitos/priorizacao/first-things-first.md
  docs/base/tap/tap.md
  docs/guia-contrib.md
  docs/politicas.md
Labels: Organização

#63 Correção dos hiperlinks das páginas do 5W2H e da Argumentação
  docs/base/requisitos/pre-rastreabilidade/5w2h.md
  docs/base/requisitos/pre-rastreabilidade/argumentacao.md
Labels: documentation

#66 Criação do documento de Sprint Review - Sprint 0
  docs/assets/imagens/sprint-review/sprint0/burndown-report.png
  docs/assets/imagens/sprint-review/sprint0/velocity-tracking.png
  docs/reunioes/sprints/review-sprint0.md
  mkdocs.yml
Labels: documentation

#68 fix(#53) Corrigindo hiperlinks do Moscow e dos Storyboards
  docs/base/requisitos/elicitacao/storyboards.md
  docs/base/requisitos/priorizacao/moscow.md
Labels: documentation, enhancement

#65 Correção dos links para os léxicos (brainstormming e guia de contribuição)
  docs/base/requisitos/elicitacao/brainstorming.md
  docs/guia-contrib.md
Labels: enhancement

#75 Correção hiperlinks especificação suplementar
  docs/base/requisitos/modelagem/especificacao-suplementar.md
Labels: enhancement

#64 Diagrama de casos de uso
  docs/assets/imagens/casos-de-uso/casos-de-uso.png
  docs/assets/imagens/casos-de-uso/componentes.png
  docs/modelagem/modelagem-dinamica/casos-de-uso.md
  mkdocs.yml
Labels: documentation

#69 Diagrama de pacote
  docs/assets/imagens/diagrama-de-pacotes/Diagrama-de-pacotes.png
  docs/modelagem/modelagem-estatica/diagrama-de-pacotes.md
  mkdocs.yml
Labels: documentation

#70 Corrigindo os hiperlinks Product Backlog
  docs/product-backlog.md
Labels: documentation

#76 Inserindo MoSCoW ao Product Backlog
  docs/product-backlog.md
Labels: documentation

#78 Criando Planning Sprint 1
  docs/reunioes/sprints/planning-sprint0.md
  docs/reunioes/sprints/planning-sprint1.md
  mkdocs.yml
Labels: documentation, Organização

#88 doc(#53): correção dos léxicos de 12 documentos.
  docs/base/design-sprint/plan-test.md
  docs/base/design-sprint/prototipo-alta.md
  docs/base/design-sprint/prototipo-baixa.md
  docs/base/design-sprint/prototipos.md
  docs/base/requisitos/modelagem/i-star.md
  docs/base/requisitos/modelagem/lexicos.md
  docs/base/requisitos/pre-rastreabilidade/5w2h.md
  docs/base/requisitos/pre-rastreabilidade/argumentacao.md
  docs/base/requisitos/pre-rastreabilidade/rich-picture.md
  docs/base/requisitos/priorizacao/first-things-first.md
  docs/base/tap/tap.md
  docs/product-backlog.md
Labels: documentation

#90 Diagrama de componentes
  docs/assets/imagens/diagrama-de-componentes/diagrama-de-componentes.png
  docs/base/design-sprint/prototipos.md
  docs/base/requisitos/modelagem/i-star.md
  docs/modelagem/modelagem-estatica/diagrama-de-componentes.md
  mkdocs.yml
Labels: documentation

#87 Modelagem do DB
  docs/assets/imagens/DER/der-conceitual-curumim.png
  docs/base/requisitos/modelagem/lexicos.md
  docs/modelagem/modelagem-estatica/DER.md
  docs/modelagem/modelagem-estatica/MER.md
  mkdocs.yml
Labels: documentation

#93 Diagrama sequencia
  docs/assets/imagens/diagrama-de-sequencia/Diagrama-de-sequencia-admin-cadastrando-prof.png
  docs/assets/imagens/diagrama-de-sequencia/Diagrama-de-sequencia-pais-responsaveis-login.png
  docs/modelagem/modelagem-dinamica/diagrama-de-sequencia.md
  mkdocs.yml
Labels: documentation

#84 Diagrama de estados
  docs/assets/imagens/diagrama-estados/cadastro-crianca-professor.png
  docs/assets/imagens/diagrama-estados/comunicacao.png
  docs/assets/imagens/diagrama-estados/gerencia-turma.png
  docs/assets/imagens/diagrama-estados/lancamento-presenca.png
  docs/modelagem/modelagem-dinamica/diagrama-estados.md
  mkdocs.yml
Labels: documentation

#95 Fazendo correções no documento de diagrama de sequencia
  docs/modelagem/modelagem-dinamica/diagrama-de-sequencia.md
Labels: documentation

#86 Diagrama de classes
  docs/assets/imagens/diagrama-de-classes/Diagrama-de-classes.png
  docs/modelagem/modelagem-estatica/diagrama-de-classes.md
  mkdocs.yml
Labels: documentation, débito técnico

#85 Diagrama de comunicação
  docs/assets/imagens/comunicacao/comunicacao-adm.png
  docs/assets/imagens/comunicacao/comunicacao-chat.png
  docs/assets/imagens/comunicacao/comunicacao-guardian.png
  docs/assets/imagens/comunicacao/comunicacao-teacher.png
  docs/assets/imagens/comunicacao/comunicação-admin.png
  docs/assets/imagens/comunicacao/comunicação-chat.png
  docs/assets/imagens/comunicacao/comunicação-prof.png
  docs/assets/imagens/comunicacao/comunicação-resp.png
  docs/modelagem/modelagem-dinamica/diagrama-de-comunicacao.md
  mkdocs.yml
Labels: documentation

#105 Correção dos diagramas de estados
  docs/assets/imagens/diagrama-estados/cadastro-crianca-professor.png
  docs/assets/imagens/diagrama-estados/lancamento-presenca.png
Labels: bug, documentation

#103 Review sprint 2
  README.md
  docs/assets/imagens/diagrama-de-classes/Diagrama-de-classes.png
  docs/assets/imagens/sobre/entrega1/wiki-imagem1.png
  docs/assets/imagens/sobre/entrega1/wiki-imagem2.png
  docs/assets/imagens/sobre/entrega1/wiki-imagem3.png
  docs/assets/imagens/sobre/entrega1/wiki-imagem4.png
  docs/assets/imagens/sobre/entrega2/img1.png
  docs/assets/imagens/sobre/entrega2/img2.png
  docs/assets/imagens/sobre/entrega2/img3.png
  docs/assets/imagens/sobre/sobre1-login.jpg
  docs/assets/imagens/sobre/sobre2-cadastro.jpg
  docs/assets/imagens/sobre/sobre3-perfil.jpg
  docs/assets/imagens/sprint-review/sprint2/burndown-report.png
  docs/assets/imagens/sprint-review/sprint2/velocity-tracking.png
  docs/modelagem/modelagem-dinamica/casos-de-uso.md
  docs/modelagem/modelagem-dinamica/diagrama-de-atividades.md
  docs/modelagem/modelagem-dinamica/diagrama-de-comunicacao.md
  docs/modelagem/modelagem-dinamica/diagrama-de-sequencia.md
  docs/modelagem/modelagem-estatica/diagrama-de-classes.md
  docs/modelagem/modelagem-estatica/diagrama-de-componentes.md
  docs/modelagem/modelagem-estatica/diagrama-de-pacotes.md
  docs/product-backlog.md
  docs/reunioes/sprints/planning-sprint2.md
  docs/reunioes/sprints/review-sprint2.md
  mkdocs.yml
Labels: documentation

#119 Doc/100 101 108 revisao joao enzo
  docs/assets/imagens/argumentacao/arg-1.png
  docs/assets/imagens/argumentacao/arg-2.png
  docs/assets/imagens/argumentacao/arg-3.png
  docs/base/design-sprint/prototipo-alta.md
  docs/base/requisitos/pre-rastreabilidade/argumentacao.md
  docs/base/requisitos/pre-rastreabilidade/mapa-mental.md
Labels: documentation

#123 Revisão dos léxicos, 5W2H, Introdução da prototipação e Design sprint
  docs/base/design-sprint/doc-design-sprint.md
  docs/base/design-sprint/prototipos.md
  docs/base/requisitos/modelagem/lexicos.md
  docs/base/requisitos/pre-rastreabilidade/5w2h.md
Labels: documentation, Feedback, Revisão

#120 Revisões do storyboard, backlog e TAP
  docs/base/requisitos/elicitacao/brainstorming.md
  docs/base/requisitos/elicitacao/introspeccao.md
  docs/base/requisitos/elicitacao/storyboards.md
  docs/base/tap/tap.md
  docs/product-backlog.md
Labels: documentation, enhancement, Feedback, Revisão

#128 Adiciona documento de modelagem lógica do banco de dados a documentação
  docs/assets/imagens/diagrama-logico-bd/diagrama-logico-bd-curumin.png
  docs/modelagem/modelagem-estatica/diagrama-logico-bd.md
  mkdocs.yml
Labels: documentation

#126 Doc/125 review sprint 3
  docs/assets/imagens/sprint-review/sprint3/burndown-report.png
  docs/assets/imagens/sprint-review/sprint3/velocity-tracking.png
  docs/reunioes/sprints/review-sprint3.md
  mkdocs.yml
Labels: documentation
